name: Docker Imge CI

on:
  pull_request:
    branches: ["main"]
  #Allow manually trigger
  workflow_dispatch:

jobs:
  build:
    runs-0n: macOS-Ventura

    steps:
      - uses: actions/checkout@v3
      - name: Build the Codespaces container image
        run: docker build . --file .devcontainer/Dockerfile
